# Generated by Django 5.0.4 on 2024-04-11 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_auction_auctionwinner_bid_auctioncategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
        migrations.DeleteModel(
            name='AuctionCategory',
        ),
    ]
