# Generated by Django 5.0.4 on 2024-05-08 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_post_like_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
